repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: stylua
        name: Stylua
        language: rust
        entry: stylua
        types: [lua]
        args: ["-"]
      - id: luacheck
        name: Luacheck
        language: system
        entry: luacheck --
        types: [lua]
